# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.9
      stages: [commit]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      stages: [commit]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
      - id: isort
        name: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        stages: [commit]

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.790  # Use the sha / tag you want to point at
#    hooks:
#    -   id: mypy
#        name: mypy
#        stages: [commit]

-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest
      pass_filenames: false
      always_run: true
      stages: [commit]
